### ISSUE TITLE
Carryforward  not working

### ISSUE THREAD

**Issue by sebas031811** [codecov/uploader#1487]
**Describe the bug**
We have a monorepo and some modules split by flags, and we use carryforward in order to merge the reports and not to override them, it was working well until 18/03/24, since that it started replacing the reports, we did not change any about codecov config

**To Reproduce**
All reports we upload replace others.

**Expected behavior**
We expect it works as before merging all reports

**Screenshots**
Main branch current
![image](https://github.com/codecov/uploader/assets/132764573/1da24e0a-8c55-45b0-903b-36918c75a5ab)
Branchs before 
![image](https://github.com/codecov/uploader/assets/132764573/d0711801-a691-4228-bf81-f7f4dde3f59f)
The commits wiew
![image](https://github.com/codecov/uploader/assets/132764573/0797e8e7-11a5-4548-9193-3793f8527832)

**Additional context**
We are using the 0.5.0 uploader version

**Comment by giovanni-guidini** [comment]
all those `commit message unavailable` indicate we are not being able to reach the provider. They use gitlab I assume?

**Comment by giovanni-guidini** [comment]
Closing this one.

For future reference (if you happen to have a similar error and is reading this thread), this is the (likely) cause of carryforward not working:

Notice in the image the many "commit message unavailable" across the commits.
This indicates that Codecov failed to get the commit information from the git provider (in this case Gitlab). Commit information includes the message and the parents of the commit.

The parents info is necessary to carryforward reports because they come from parent to child. Because Codecov didn't have that info when creating reports for these new commits it didn't carried forward previous reports.
